# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "LICENSE.txt", "_stage"]
highlighter: 'rouge' 

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
include: ['_pages']

baseurl: https://docs.oneconnexx.com
github_repo_url: https://github.com/Sevitec/oneconnexx-docs/

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
